### ISSUE TITLE
Will this work on a subword level?

### ISSUE THREAD

**Issue by LearnedVector** [iamjanvijay/rnnt_decoder_cuda#1]
Hello! Thanks for the repo! Will this implementation work on a subword level?

**Comment by iamjanvijay** [comment]
@LearnedVector Yes! I implemented this for subword level only (subword vocab size 5K). Here is the subword list used in the dummy run: https://github.com/iamjanvijay/rnnt_decoder_cuda/blob/master/data/params/vocab_list.txt

**Comment by LearnedVector** [comment]
awesome! thanks!
